/**
 * This class is generated by jOOQ
 */
package com.db.pojo.tables.records;


import com.db.pojo.tables.EhUrlMapping;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUrlMappingRecord extends UpdatableRecordImpl<EhUrlMappingRecord> implements Record7<Long, String, String, Long, Timestamp, Timestamp, Byte> {

    private static final long serialVersionUID = -533089736;

    /**
     * Setter for <code>eh_short_url.eh_url_mapping.id</code>. 主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh_short_url.eh_url_mapping.id</code>. 主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh_short_url.eh_url_mapping.short_url</code>. 短链接
     */
    public void setShortUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh_short_url.eh_url_mapping.short_url</code>. 短链接
     */
    public String getShortUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>eh_short_url.eh_url_mapping.long_url</code>. 长链接
     */
    public void setLongUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh_short_url.eh_url_mapping.long_url</code>. 长链接
     */
    public String getLongUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eh_short_url.eh_url_mapping.url_id</code>. url唯一id
     */
    public void setUrlId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh_short_url.eh_url_mapping.url_id</code>. url唯一id
     */
    public Long getUrlId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>eh_short_url.eh_url_mapping.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh_short_url.eh_url_mapping.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>eh_short_url.eh_url_mapping.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh_short_url.eh_url_mapping.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>eh_short_url.eh_url_mapping.status</code>. 链接状态：0：无效，1：生效
     */
    public void setStatus(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh_short_url.eh_url_mapping.status</code>. 链接状态：0：无效，1：生效
     */
    public Byte getStatus() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Long, Timestamp, Timestamp, Byte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Long, Timestamp, Timestamp, Byte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EhUrlMapping.EH_URL_MAPPING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EhUrlMapping.EH_URL_MAPPING.SHORT_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EhUrlMapping.EH_URL_MAPPING.LONG_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return EhUrlMapping.EH_URL_MAPPING.URL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return EhUrlMapping.EH_URL_MAPPING.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return EhUrlMapping.EH_URL_MAPPING.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return EhUrlMapping.EH_URL_MAPPING.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getShortUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLongUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getUrlId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EhUrlMappingRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EhUrlMappingRecord value2(String value) {
        setShortUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EhUrlMappingRecord value3(String value) {
        setLongUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EhUrlMappingRecord value4(Long value) {
        setUrlId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EhUrlMappingRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EhUrlMappingRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EhUrlMappingRecord value7(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EhUrlMappingRecord values(Long value1, String value2, String value3, Long value4, Timestamp value5, Timestamp value6, Byte value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EhUrlMappingRecord
     */
    public EhUrlMappingRecord() {
        super(EhUrlMapping.EH_URL_MAPPING);
    }

    /**
     * Create a detached, initialised EhUrlMappingRecord
     */
    public EhUrlMappingRecord(Long id, String shortUrl, String longUrl, Long urlId, Timestamp createTime, Timestamp updateTime, Byte status) {
        super(EhUrlMapping.EH_URL_MAPPING);

        set(0, id);
        set(1, shortUrl);
        set(2, longUrl);
        set(3, urlId);
        set(4, createTime);
        set(5, updateTime);
        set(6, status);
    }
}
