/**
 * This class is generated by jOOQ
 */
package com.db.pojo.tables.daos;


import com.db.pojo.tables.EhUrlMapping;
import com.db.pojo.tables.records.EhUrlMappingRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUrlMappingDao extends DAOImpl<EhUrlMappingRecord, com.db.pojo.tables.pojos.EhUrlMapping, Long> {

    /**
     * Create a new EhUrlMappingDao without any configuration
     */
    public EhUrlMappingDao() {
        super(EhUrlMapping.EH_URL_MAPPING, com.db.pojo.tables.pojos.EhUrlMapping.class);
    }

    /**
     * Create a new EhUrlMappingDao with an attached configuration
     */
    public EhUrlMappingDao(Configuration configuration) {
        super(EhUrlMapping.EH_URL_MAPPING, com.db.pojo.tables.pojos.EhUrlMapping.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.db.pojo.tables.pojos.EhUrlMapping object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.db.pojo.tables.pojos.EhUrlMapping> fetchById(Long... values) {
        return fetch(EhUrlMapping.EH_URL_MAPPING.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.db.pojo.tables.pojos.EhUrlMapping fetchOneById(Long value) {
        return fetchOne(EhUrlMapping.EH_URL_MAPPING.ID, value);
    }

    /**
     * Fetch records that have <code>short_url IN (values)</code>
     */
    public List<com.db.pojo.tables.pojos.EhUrlMapping> fetchByShortUrl(String... values) {
        return fetch(EhUrlMapping.EH_URL_MAPPING.SHORT_URL, values);
    }

    /**
     * Fetch records that have <code>long_url IN (values)</code>
     */
    public List<com.db.pojo.tables.pojos.EhUrlMapping> fetchByLongUrl(String... values) {
        return fetch(EhUrlMapping.EH_URL_MAPPING.LONG_URL, values);
    }

    /**
     * Fetch records that have <code>url_id IN (values)</code>
     */
    public List<com.db.pojo.tables.pojos.EhUrlMapping> fetchByUrlId(Long... values) {
        return fetch(EhUrlMapping.EH_URL_MAPPING.URL_ID, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.db.pojo.tables.pojos.EhUrlMapping> fetchByCreateTime(Timestamp... values) {
        return fetch(EhUrlMapping.EH_URL_MAPPING.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.db.pojo.tables.pojos.EhUrlMapping> fetchByUpdateTime(Timestamp... values) {
        return fetch(EhUrlMapping.EH_URL_MAPPING.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.db.pojo.tables.pojos.EhUrlMapping> fetchByStatus(Byte... values) {
        return fetch(EhUrlMapping.EH_URL_MAPPING.STATUS, values);
    }
}
