/**
 * This class is generated by jOOQ
 */
package com.db.pojo;


import com.db.pojo.tables.EhUrlMapping;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhShortUrl extends SchemaImpl {

    private static final long serialVersionUID = 1606575496;

    /**
     * The reference instance of <code>eh_short_url</code>
     */
    public static final EhShortUrl EH_SHORT_URL = new EhShortUrl();

    /**
     * The table <code>eh_short_url.eh_url_mapping</code>.
     */
    public final EhUrlMapping EH_URL_MAPPING = com.db.pojo.tables.EhUrlMapping.EH_URL_MAPPING;

    /**
     * No further instances allowed
     */
    private EhShortUrl() {
        super("eh_short_url", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            EhUrlMapping.EH_URL_MAPPING);
    }
}
