/**
 * This class is generated by jOOQ
 */
package com.db.pojo;


import com.db.pojo.tables.EhUrlMapping;
import com.db.pojo.tables.records.EhUrlMappingRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>eh_short_url</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EhUrlMappingRecord, Long> IDENTITY_EH_URL_MAPPING = Identities0.IDENTITY_EH_URL_MAPPING;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EhUrlMappingRecord> KEY_EH_URL_MAPPING_PRIMARY = UniqueKeys0.KEY_EH_URL_MAPPING_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<EhUrlMappingRecord, Long> IDENTITY_EH_URL_MAPPING = createIdentity(EhUrlMapping.EH_URL_MAPPING, EhUrlMapping.EH_URL_MAPPING.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<EhUrlMappingRecord> KEY_EH_URL_MAPPING_PRIMARY = createUniqueKey(EhUrlMapping.EH_URL_MAPPING, "KEY_eh_url_mapping_PRIMARY", EhUrlMapping.EH_URL_MAPPING.ID);
    }
}
