/**
 * This class is generated by jOOQ
 */
package com.db.pojo;


import com.db.pojo.tables.EhUrlMapping;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in eh_short_url
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>eh_short_url.eh_url_mapping</code>.
     */
    public static final EhUrlMapping EH_URL_MAPPING = com.db.pojo.tables.EhUrlMapping.EH_URL_MAPPING;
}
