/**
 * This class is generated by jOOQ
 */
package com.db.pojo.tables;


import com.db.pojo.EhShortUrl;
import com.db.pojo.Keys;
import com.db.pojo.tables.records.EhUrlMappingRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUrlMapping extends TableImpl<EhUrlMappingRecord> {

    private static final long serialVersionUID = -1915199306;

    /**
     * The reference instance of <code>eh_short_url.eh_url_mapping</code>
     */
    public static final EhUrlMapping EH_URL_MAPPING = new EhUrlMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EhUrlMappingRecord> getRecordType() {
        return EhUrlMappingRecord.class;
    }

    /**
     * The column <code>eh_short_url.eh_url_mapping.id</code>. 主键id
     */
    public final TableField<EhUrlMappingRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "主键id");

    /**
     * The column <code>eh_short_url.eh_url_mapping.short_url</code>. 短链接
     */
    public final TableField<EhUrlMappingRecord, String> SHORT_URL = createField("short_url", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "短链接");

    /**
     * The column <code>eh_short_url.eh_url_mapping.long_url</code>. 长链接
     */
    public final TableField<EhUrlMappingRecord, String> LONG_URL = createField("long_url", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "长链接");

    /**
     * The column <code>eh_short_url.eh_url_mapping.url_id</code>. url唯一id
     */
    public final TableField<EhUrlMappingRecord, Long> URL_ID = createField("url_id", org.jooq.impl.SQLDataType.BIGINT, this, "url唯一id");

    /**
     * The column <code>eh_short_url.eh_url_mapping.create_time</code>. 创建时间
     */
    public final TableField<EhUrlMappingRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>eh_short_url.eh_url_mapping.update_time</code>. 更新时间
     */
    public final TableField<EhUrlMappingRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * The column <code>eh_short_url.eh_url_mapping.status</code>. 链接状态：0：无效，1：生效
     */
    public final TableField<EhUrlMappingRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT, this, "链接状态：0：无效，1：生效");

    /**
     * Create a <code>eh_short_url.eh_url_mapping</code> table reference
     */
    public EhUrlMapping() {
        this("eh_url_mapping", null);
    }

    /**
     * Create an aliased <code>eh_short_url.eh_url_mapping</code> table reference
     */
    public EhUrlMapping(String alias) {
        this(alias, EH_URL_MAPPING);
    }

    private EhUrlMapping(String alias, Table<EhUrlMappingRecord> aliased) {
        this(alias, aliased, null);
    }

    private EhUrlMapping(String alias, Table<EhUrlMappingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return EhShortUrl.EH_SHORT_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EhUrlMappingRecord, Long> getIdentity() {
        return Keys.IDENTITY_EH_URL_MAPPING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EhUrlMappingRecord> getPrimaryKey() {
        return Keys.KEY_EH_URL_MAPPING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EhUrlMappingRecord>> getKeys() {
        return Arrays.<UniqueKey<EhUrlMappingRecord>>asList(Keys.KEY_EH_URL_MAPPING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EhUrlMapping as(String alias) {
        return new EhUrlMapping(alias, this);
    }

    /**
     * Rename this table
     */
    public EhUrlMapping rename(String name) {
        return new EhUrlMapping(name, null);
    }
}
