/**
 * This class is generated by jOOQ
 */
package com.db.pojo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUrlMapping implements Serializable {

    private static final long serialVersionUID = -32289781;

    private Long      id;
    private String    shortUrl;
    private String    longUrl;
    private Long      urlId;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Byte      status;

    public EhUrlMapping() {}

    public EhUrlMapping(EhUrlMapping value) {
        this.id = value.id;
        this.shortUrl = value.shortUrl;
        this.longUrl = value.longUrl;
        this.urlId = value.urlId;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.status = value.status;
    }

    public EhUrlMapping(
        Long      id,
        String    shortUrl,
        String    longUrl,
        Long      urlId,
        Timestamp createTime,
        Timestamp updateTime,
        Byte      status
    ) {
        this.id = id;
        this.shortUrl = shortUrl;
        this.longUrl = longUrl;
        this.urlId = urlId;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.status = status;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getShortUrl() {
        return this.shortUrl;
    }

    public void setShortUrl(String shortUrl) {
        this.shortUrl = shortUrl;
    }

    public String getLongUrl() {
        return this.longUrl;
    }

    public void setLongUrl(String longUrl) {
        this.longUrl = longUrl;
    }

    public Long getUrlId() {
        return this.urlId;
    }

    public void setUrlId(Long urlId) {
        this.urlId = urlId;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EhUrlMapping (");

        sb.append(id);
        sb.append(", ").append(shortUrl);
        sb.append(", ").append(longUrl);
        sb.append(", ").append(urlId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
